### ISSUE TITLE
Use of deprecated antialiasing in displayCoverArt.py

### ISSUE THREAD

**Issue by rohithm8** [ryanwa18/spotipi#18]
In the latest version of pillow, the `Image.ANTIALIAS` method has been replaced by `Image.LANCZOS`. This may be worth updating in `displayCoverArt.py` as it appears a few times here, and the installation script does not specify a specific version of pillow.

(Thanks for putting the effort into this library btw was super easy to get up and running!)

**Comment by ryanwa18** [comment]
Fixed
