### ISSUE TITLE
ImportError: No module named transferImage

### ISSUE THREAD

**Issue by DavidHersh** [ryanwa18/spotipi#2]
When running: sudo --preserve-env python displayCoverArt.py <spotify username> 
I get the following error:
Traceback (most recent call last):
  File "displayCoverArt.py", line 6, in <module>
    from getSongInfo import getSongInfo
  File "/home/pi/spotipi/python/getSongInfo.py", line 9, in <module>
    from transferImage import display
ImportError: No module named transferImage

**Comment by ryanwa18** [comment]
Just updated the install to remove that line as it is no longer needed. Thanks for the issue!
