### ISSUE TITLE
Matrix doesn't seem to respond...

### ISSUE THREAD

**Issue by vdimarco** [ryanwa18/spotipi#22]
I can see the service is successfully running on the Pi. I'm able to access the app via the web browser. But it's not responsive  lighting up. No idea as how to debug this. Any advice?

**Comment by tklein243** [comment]
I am having the same exact issue. Any news on this

**Comment by lukedokic** [comment]
Me too nothing showing

**Comment by vdimarco** [comment]
Figured this out. For me it was the fact that https://github.com/hzeller/rpi-rgb-led-matrix wasn't installed

**Comment by vdimarco** [comment]
Figured this out. For me it was the fact that https://github.com/hzeller/rpi-rgb-led-matrix wasn't installed
