### ISSUE TITLE
Flickering matrix panels

### ISSUE THREAD

**Issue by flasher69** [ryanwa18/spotipi#5]
Hi Ryan,

great project. I really love it and also thank you for your great youtube video. I had some problems creating the token under OS X but under virtual environment I was able to get rid of the errors.
I have a small issue. I release that there are little bit of flickerings on the screen. I'm using Adafruit bonnet and I have connected the pins for the better resolution. I've also selected quality option for installation. Where can I find the settings for matrix display in your script? 

Btw is there a way to make bigger displays such as 128 x 128 ( 4 x matrices 64 x 64)?

Again thank for for this great work

**Comment by tedharrison-rpc** [comment]
@flasher69 I would check over at the main rgb matrix repository for tips on fixing the flickering issue: https://github.com/hzeller/rpi-rgb-led-matrix

Also, this file is where the code for rgb-options is located i think: https://github.com/ryanwa18/spotipi/blob/develop/config/rgb_options.ini

**Comment by flasher69** [comment]
> @flasher69 I would check over at the main rgb matrix repository for tips on fixing the flickering issue: https://github.com/hzeller/rpi-rgb-led-matrix
> 
> Also, this file is where the code for rgb-options is located i think: https://github.com/ryanwa18/spotipi/blob/develop/config/rgb_options.ini

Thanx tward212. I set the slow down of gpio to 4. It's still has a bit of flickering. I'm using a RPI zero W. Maybe it's just not strong enough. I'll try other devices

**Comment by ryanwa18** [comment]
Hey guys, I appreciate your open ticket on this issue. This is something I have yet to quite figure out myself. My panels still seem to slightly flicker with the older Raspberry Pi Zero. 

As for bigger displays, I would imagine that this could work assuming you have enough power to supply the Pi and the matrix. You can try changing this file [https://github.com/ryanwa18/spotipi/blob/develop/config/rgb_options.ini](https://github.com/ryanwa18/spotipi/blob/develop/config/rgb_options.ini ) with the height and width as 128.

**Comment by flasher69** [comment]
Hey Ryan,
About the bigger images on 2 Panels of 64 x 64 I didn't have so much success yet. I'm also not sure if editing rgb_options.ini really changes. Somehow I think there is a conflict with other parameters in other places/scripts. I'll post here if I find a solution.

**Comment by flasher69** [comment]
![2021-12-20 19 45 46](https://user-images.githubusercontent.com/22278347/146820561-f889886a-f6e3-4dc0-88bc-4f1c6729498e.jpg)
okay, I've tested different Raspberry Pis and Rpi4 seems to be strong enough so there is no flickering. 
Btw I was able to use 4 Hub75 (128 x 128) and make a bigger display. I'm not using a Adafruit Bonnet but a Joy-it control board. Here is the link: https://joy-it.net/en/products/RB-MatrixCtrl

Here is the settings for rgb_options.ini:

DEFAULT]
rows = 64
columns = 128
chain_length = 1
parallel = 2
hardware_mapping = regular
gpio_slowdown = 4
brightness = 70
default_image = ../images/default.png
power = on

**Comment by mraess** [comment]
> ![2021-12-20 19 45 46](https://user-images.githubusercontent.com/22278347/146820561-f889886a-f6e3-4dc0-88bc-4f1c6729498e.jpg) okay, I've tested different Raspberry Pis and Rpi4 seems to be strong enough so there is no flickering. Btw I was able to use 4 Hub75 (128 x 128) and make a bigger display. I'm not using a Adafruit Bonnet but a Joy-it control board. Here is the link: https://joy-it.net/en/products/RB-MatrixCtrl
> 
> Here is the settings for rgb_options.ini:
> 
> DEFAULT] rows = 64 columns = 128 chain_length = 1 parallel = 2 hardware_mapping = regular gpio_slowdown = 4 brightness = 70 default_image = ../images/default.png power = on

Hi @flasher69 thanks for the setting instructions! Did you have to re-run the entire spotipi install process after changing the .ini file or just re-boot your Pi?

**Comment by flasher69** [comment]
> > ![2021-12-20 19 45 46](https://user-images.githubusercontent.com/22278347/146820561-f889886a-f6e3-4dc0-88bc-4f1c6729498e.jpg) okay, I've tested different Raspberry Pis and Rpi4 seems to be strong enough so there is no flickering. Btw I was able to use 4 Hub75 (128 x 128) and make a bigger display. I'm not using a Adafruit Bonnet but a Joy-it control board. Here is the link: https://joy-it.net/en/products/RB-MatrixCtrl
> > Here is the settings for rgb_options.ini:
> > DEFAULT] rows = 64 columns = 128 chain_length = 1 parallel = 2 hardware_mapping = regular gpio_slowdown = 4 brightness = 70 default_image = ../images/default.png power = on
> 
> Hi @flasher69 thanks for the setting instructions! Did you have to re-run the entire spotipi install process after changing the .ini file or just re-boot your Pi?

I just did a reboot after editing the rgb_options.ini. No need to install anything. Btw I was using a HAT from Joy-It. I have a Adafruit Bonnet but I didn't try if it works with four panels too.

**Comment by mraess** [comment]
@flasher69 thanks for your quick reply. Yeah, it'd be interesting if the Bonnet can handle just chaining four panels together.
