### ISSUE TITLE
Help with generate-token.sh

### ISSUE THREAD

**Issue by tedharrison-rpc** [ryanwa18/spotipi#6]
Hey Ryan,

I appreciate you putting this project together, it seems really cool.  

Unfortunately for me, I've been beating my head against the wall for the last few weeks trying to get the correct .cache-<username> file created.  I keep hitting a variety of snags including:

Not being redirected to a url that I can copy
Not being asked to upload a url at all by the script
and now I'm getting hit with the following error: 

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 588, in refresh_access_token
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/spotipi/python/generateToken.py", line 8, in <module>
    token = util.prompt_for_user_token(username, scope)
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/util.py", line 96, in prompt_for_user_token
    token_info = sp_oauth.validate_token(sp_oauth.cache_handler.get_cached_token())
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 380, in validate_token
    token_info = self.refresh_access_token(
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 596, in refresh_access_token
    self._handle_oauth_error(http_error)
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_client, error_description: Invalid client
`
Not sure what is happening here and I've reentered my client ID, etc. multiple times and triple checked to make sure it's correct.

Any advice would be greatly appreciated.

Thanks!

**Comment by ryanwa18** [comment]
Hey!

I am really glad that you think the project is cool. 

I have a feeling that the version of python you are using "3.9" might be causing the issue. I currently run and test the 'generate.sh' script on a macbook which runs `Python 2.7.10`.

I would suggest trying to use `Python 2.7.10` when you run the `generate-token.sh` script.

Let me know if that fixes your issue!

**Comment by tedharrison-rpc** [comment]
Hey Ryan, thanks for the response! It took me a while to get back to this project because of work, but now I'm troubleshooting it again.

Fortunately, I fixed the issue I was dealing with in the previous comment.

However, I'm now hitting another dead end related to the following error:

```
Traceback (most recent call last):
  File "python/generateToken.py", line 2, in <module>
    import spotipy
ImportError: No module named spotipy 
```

Some cursory research shows that there is probably something wrong with the python PATH, but beyond that I'm not sure what to do to fix it.  It seems like the ``` spotipy ``` module is being put here: ``` /.local/lib/python3.9 ```

So, I'm stumped at this point, but think once I fix this one I should be good to go, so any helpful insights would be greatly appreciated.

Thanks!
