### ISSUE TITLE
Python3 Compatibiliy

### ISSUE THREAD

**Issue by Jordinho** [ryanwa18/spotipi#7]
Hi Ryan,

Thanks for all the effort for this post and the youtube videos you made.  I enjoyed them.

Have you tried to run this on python3.8 or 3.9?  I think I read somewhere you were using 2.7.10?

I ran your script but could not display anything on the led (i have done several other led matrix projects successfully).  Through debugging I saw some warnings/errors that I think were caused by the new python version.

**Comment by ryanwa18** [comment]
Yeah I made a comment about it in a previous issue. I would imagine that the rgb matrix library that is being used does not yet support the latest version of python. 

I haven’t had time to look into this issue further but that would be my best guess. For now I would recommend installing an older version OS that still uses python 2.7

**Comment by frod0r** [comment]
The library from which adafruit forked their version actually has python3 support, see https://github.com/hzeller/rpi-rgb-led-matrix/tree/a93acf26990ad6794184ed8c9487ab2a5c39cd28/bindings/python

Building those bindings and then using your library with python3 worked like a charm for me after some [minor adjustments](https://github.com/frod0r/spotipi-homassistant/commit/d370c5d90f3fbbdc82259a8c5b3ed2bda3ce039f)
